services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.10
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
